P3 297 implement upload api
wisework/wisework-open-api pull request #41
Opened 2023-06-27 11:21 UTC by PRP-4979

Added error handle on upload endpoint

2023-06-28 03:10 UTC, sapanisaradamjan requested changes

2023-06-28 03:10 UTC, sapanisaradamjan commented on src/Application/Upload/Commands/UploadFile/UploadFileCommand.cs
> +    [JsonIgnore]
line 20 ลบ ออก นะ แต่ถ้าจะใช้ [JsonIgnore] แทนของพี่ให้เอาไปใส่ใน class AuthenticationModel แทนของพี่

2023-06-28 07:24 UTC, PRP-4979 commented on src/Application/Upload/Commands/UploadFile/UploadFileCommand.cs
> +    [JsonIgnore]
<img width="242" alt="Screenshot 2023-06-28 142236" src="https://github.com/wisework/wisework-open-api/assets/68856496/725127d7-b58b-42ed-9819-bd3a5b655fa2">

ต้องใส่ทั้งคู่คับ เพราะ [JsonIgnore] จะเป็นการปิดตรงที่เป็น Request Body 
ส่วน [OpenApiIgnoreAttribute] จะปิดตรง Parameter

2023-06-29 04:20 UTC, sapanisaradamjan approved these changes

2023-06-29 04:34 UTC, merged